apiVersion: v1
kind: Secret
metadata:
  name: coffee-shop
  annotations:
    argocd.argoproj.io/sync-wave: "2"
stringData:
  quarkus.datasource.db-kind: postgresql
  quarkus.datasource.jdbc.url: jdbc:postgresql://coffee-shop-database:5432/coffeeshop
  quarkus.datasource.password: coffee
  quarkus.datasource.username: coffee
