apiVersion: apps/v1
kind: Deployment
metadata:
  name: coffee-shop
spec:
  template:
    spec:
      containers:
      - name: coffee-shop
        image: quay.io/agoossen/coffee-shop:prod-2022-02-21-04-24-56

