apiVersion: apps/v1
kind: Deployment
metadata:
  name: coffee-shop
spec:
  template:
    spec:
      containers:
      - name: coffee-shop
        image: quay.io/agoossen/coffee-shop:prod-2021-11-25-23-52-47

