apiVersion: apps/v1
kind: Deployment
metadata:
  name: coffee-shop
spec:
  template:
    spec:
      containers:
      - name: coffee-shop
        image: homework-nexus-registry.apps.shared-dev4.dev4.openshift.opentlc.com/jz9h8-coffee-shop:prod-2021-11-19-04-16-50

