apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: barista
spec:
  template:
    spec:
      containers:
      - name: user-container
        image: quay.io/agoossen/coffee-shop:prod-2021-11-29-09-58-43

