apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: barista
spec:
  template:
    spec:
      containers:
      - name: user-container
        image: quay.io/agoossen/barista:prod-2022-02-16-06-35-35

